// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskApi.DataAccess;

namespace TaskApi.DataAccess.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20210813180925_job role field added to author")]
    partial class jobrolefieldaddedtoauthor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskApi.Modals.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressNo = "45",
                            City = "Colombo 1",
                            FullName = "Thenuka Jayarathna",
                            JobRole = "Developer",
                            Street = "street 1"
                        },
                        new
                        {
                            Id = 2,
                            AddressNo = "22",
                            City = "Colombo 5",
                            FullName = "Pubudu Gamage",
                            JobRole = "Systems Engineer",
                            Street = "street 2"
                        },
                        new
                        {
                            Id = 3,
                            AddressNo = "14",
                            City = "Kandy",
                            FullName = "Nishadi Hansika",
                            JobRole = "Developer",
                            Street = "street 4"
                        },
                        new
                        {
                            Id = 4,
                            AddressNo = "55",
                            City = "Nugegoda",
                            FullName = "Nipun Gallage",
                            JobRole = "QA",
                            Street = "street 5"
                        },
                        new
                        {
                            Id = 5,
                            AddressNo = "422/1",
                            City = "Galle",
                            FullName = "Isuru Anjana",
                            JobRole = "Developer",
                            Street = "street 6"
                        });
                });

            modelBuilder.Entity("TaskApi.Modals.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2021, 8, 13, 23, 39, 25, 16, DateTimeKind.Local).AddTicks(6069),
                            Description = "Get some text books for school",
                            Due = new DateTime(2021, 8, 18, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(4483),
                            Status = 0,
                            Title = "Get books for school"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            Created = new DateTime(2021, 8, 13, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5395),
                            Description = "Get some food for next week",
                            Due = new DateTime(2021, 8, 16, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5400),
                            Status = 0,
                            Title = "Shopping for next week"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Created = new DateTime(2021, 8, 13, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5407),
                            Description = "Practice programming",
                            Due = new DateTime(2021, 8, 15, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5409),
                            Status = 0,
                            Title = "Do some programming practice"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Created = new DateTime(2021, 8, 13, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5410),
                            Description = "Clean the room",
                            Due = new DateTime(2021, 8, 18, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5411),
                            Status = 0,
                            Title = "Clean room"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            Created = new DateTime(2021, 8, 13, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5413),
                            Description = "Finish daily workout",
                            Due = new DateTime(2021, 8, 14, 23, 39, 25, 17, DateTimeKind.Local).AddTicks(5414),
                            Status = 0,
                            Title = "Workout for 30 minutes"
                        });
                });

            modelBuilder.Entity("TaskApi.Modals.Todo", b =>
                {
                    b.HasOne("TaskApi.Modals.Author", "Author")
                        .WithMany("Todos")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TaskApi.Modals.Author", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
